### ISSUE TITLE
URGENT - Creation alertingProfiles : error "unsupported protocol scheme"

### ISSUE THREAD

**Issue by blaurendeau** [dynatrace-oss/terraform-provider-dynatrace#118] opened 2022-03-27 13:27 UTC
Bonjour,

  I just want to create an alerting profile, and i post return error _**"alertingProfiles": unsupported protocol scheme "**_

 i don't try to create something complexe
 
 Cordialement

---------------------------------------------------------------------------------------------------------
`Terraform will perform the following actions:

  '#module.brief_alerting_profile_ops.dynatrace_alerting_profile.alerting_support_group_ops will be created
  + resource "dynatrace_alerting_profile" "alerting_support_group_ops" {
      + display_name = "support_group-ops-test"
      + id           = (known after apply)
      + mz_id        = "-5822071696614305706"

      + rules {
          + delay_in_minutes = 0
          + severity_level   = "CUSTOM_ALERT"

          + tag_filter {
              + include_mode = "NONE"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "dynatrace-framework_cs-monitoring"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.brief_alerting_profile_ops.dynatrace_alerting_profile.alerting_support_group_ops: Creating...
╷
│ Error: Post "%3Csee%20standard%3E/api/config/v1/alertingProfiles": unsupported protocol scheme ""
│ 
│   with module.brief_alerting_profile_ops.dynatrace_alerting_profile.alerting_support_group_ops,
│   on .terraform/modules/brief_alerting_profile_ops/modules/module_dynatrace_alerting_profile_ops/main.tf line 16, in resource "dynatrace_alerting_profile" "alerting_support_group_ops":
│   16: resource "dynatrace_alerting_profile" "alerting_support_group_ops" {
│ 
 `

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-03-28 08:30
Hello @blaurendeau ,

I've responded to you via email about a few details within your configuration - just in case you don't want to share that on a public GitHub issue.

Waiting for your response.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-03-28 09:37
Closing this ticket as the issue is not a but and got resolved via email.

**Closed by Dynatrace-Reinhard-Pilz** 2022-03-28 09:37 UTC
Labels: help wanted
