### ISSUE TITLE
Issue with dynatrace_autotag module 

### ISSUE THREAD

**Issue by SolalVall** [dynatrace-oss/terraform-provider-dynatrace#132] opened 2022-05-20 18:59 UTC
Hello,

Since few days, my team and I are observing a bug with the autotag rules. The order of the `rules` keeps changing and each time we run a `terraform plan` the output is different.

When we are not adding/removing or modifying  new rules, running `terraform apply` seems to not change anything in Dynatrace even if terraform has detected some changes with the `rules` order.

#### Dynatrace UI
![Screen Shot 2022-05-20 at 2 46 11 PM](https://user-images.githubusercontent.com/14978214/169592945-171cdb9d-a12f-42c8-b06d-a9d27fc43a24.png)

#### Running a first `terraform plan` and `terraform apply`
```
  ~ resource "dynatrace_autotag" "autotag" {
        id   = "7d9754dd-1d5a-400b-8b41-f5b6829f3400"
        name = "test"

      ~ rules {
            # (4 unchanged attributes hidden)

          ~ conditions {


              ~ string {
                  ~ value          = "foo" -> "bar"
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }
      ~ rules {
            # (4 unchanged attributes hidden)

          ~ conditions {


              ~ string {
                  ~ value          = "foo-bar" -> "foo"
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }
      ~ rules {
            # (4 unchanged attributes hidden)

          ~ conditions {


              ~ string {
                  ~ value          = "bar" -> "foo-bar"
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }
    }
```
#### Dynatrace UI after first `plan/apply`

:warning: no changes

![Screen Shot 2022-05-20 at 2 46 11 PM](https://user-images.githubusercontent.com/14978214/169592945-171cdb9d-a12f-42c8-b06d-a9d27fc43a24.png)

#### Running a second `terraform plan` and `terraform apply`

:warning: the plan is even different than the first one

```
**  # module.Team_autotag.dynatrace_autotag.autotag[0] has changed
  ~ resource "dynatrace_autotag" "autotag" {
        id   = "7d9754dd-1d5a-400b-8b41-f5b6829f3400"
        name = "test"

      ~ rules {
            # (4 unchanged attributes hidden)

          ~ conditions {


              ~ string {
                  ~ value          = "bar" -> "foo"
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }
      ~ rules {
            # (4 unchanged attributes hidden)

          ~ conditions {


              ~ string {
                  ~ value          = "foo" -> "bar"
                    # (3 unchanged attributes hidden)
                }
                # (1 unchanged block hidden)
            }
        }
        # (1 unchanged block hidden)
    }
```

And again no changes in the ui 😕 

## Various

- We are using a `set` for the `dynamic "rules"` definition (to ensure a correct order).
- Terraform version: Terraform v1.1.5
- Modules version: 1.11.0
- We've noticed a change with the autotag workflow in the Dynatrace UI, so maybe our current issue is related to that change:

#### Dynatrace UI autotag configuration (old version)
![post-example-1037-c1e96c6209](https://user-images.githubusercontent.com/14978214/169594050-40034f40-d850-477e-af59-70fd6792dd68.png)

#### Dynatrace UI autotag configuration (new version)
![Screen Shot 2022-05-20 at 2 57 19 PM](https://user-images.githubusercontent.com/14978214/169594322-24dae859-21bb-47f4-9cbf-5ea011ecdaa1.png)

Thanks in advance for looking at this issue and please let me know if you need more details.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-06-03 12:54
Hello @SolalVall ,

Sorry for taking so long to react.
If I'm not terribly wrong, the root cause for your issues is, that the Dynatrace REST API for some reason doesn't necessarily deliver the rules (and the conditions within these rules) in a predictable order. This used to be the case until recently.

With Release 1.11.1 the Terraform Provider takes care of sorting the configured rules in a predictable manner (to be very specific, the string representations of the rules determine their order).
With this approach it is of course still possible to get a non-empty plan initially - after all the order of the rules in your module may not align with the order the Terraform Provider has chosen. It's therefore very likely that you have to adjust the rules and the conditions within these rules once, before things are aligned.

The alternative for this solution would have been to specify the Rules within the Schema not as a list but as a set. The disadvantage of that approach is however, that entries within such sets are restricted to be primitive data types (number, strings, ...). If the entries within such a set are themselves based on a Schema, validation of the contents becomes unavailable.

I'm looking for ways to work around these limitations (also an issue in other resources offered by this provider), but the solution of at least enforcing a predictable sort order (instead of keeping users at the mercy of the REST API) is the best I can do on short notice.

Let me know if 1.11.1 indeed takes care of your issues. If not, please provide your exact HCL file for me to test locally.

best regards,
Reinhard

**Comment by gmichels** [comment] 2022-10-11 18:09
I am using 1.13.2 and still having this issue. In fact, the autotags are generated by the export functionality, for which I am using them verbatim.

I have quite a few rules, for which I provide them below (removed contextual info),

```
### SOLUTION
resource "dynatrace_autotag" "Solution" {
  name = "Solution"
  entity_selector_based_rule {
    enabled      = true
    selector     = "type(\"CLOUD_APPLICATION\"),entityName(\"app1\")"
    unknowns     = "{\"normalization\":\"LEAVE_TEXT_AS_IS\"}"
    value_format = "Solution-B"
  }
  rules {
    type          = "APPLICATION"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "WEB_APPLICATION_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "CONTAINS"
        value    = "Solution-A"
      }
    }
  }
  rules {
    type              = "SERVICE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["SERVICE_TO_PROCESS_GROUP_LIKE"]
    value_format      = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "CONTAINS"
        value    = "solution-a"
      }
    }
  }
  rules {
    type              = "SERVICE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["SERVICE_TO_PROCESS_GROUP_LIKE"]
    value_format      = "Solution-C"
    conditions {
      process_metadata {
        attribute   = "PROCESS_GROUP_PREDEFINED_METADATA"
        dynamic_key = "KUBERNETES_BASE_POD_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "app1|app2|app3|app4|app5|app6|app7"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-C"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_DATABASE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "db1|db2|db3"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type              = "PROCESS_GROUP"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["PROCESS_GROUP_TO_HOST", "PROCESS_GROUP_TO_SERVICE"]
    value_format      = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "HOST_DETECTED_NAME"
      }
      string {
        case_sensitive = true
        # negate = false
        operator = "BEGINS_WITH"
        value    = "SB"
      }
    }
  }
  rules {
    type          = "APPLICATION"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "WEB_APPLICATION_NAME"
      }
      string {
        case_sensitive = true
        # negate = false
        operator = "BEGINS_WITH"
        value    = "Solution-B"
      }
    }
  }
  rules {
    type              = "PROCESS_GROUP"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["PROCESS_GROUP_TO_HOST", "PROCESS_GROUP_TO_SERVICE"]
    value_format      = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "HOST_GROUP_NAME"
      }
      string {
        case_sensitive = true
        # negate = false
        operator = "BEGINS_WITH"
        value    = "KB"
      }
    }
  }
  rules {
    type              = "PROCESS_GROUP"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["PROCESS_GROUP_TO_HOST", "PROCESS_GROUP_TO_SERVICE"]
    value_format      = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "HOST_GROUP_NAME"
      }
      string {
        case_sensitive = true
        # negate = false
        operator = "BEGINS_WITH"
        value    = "sb-"
      }
    }
  }
  rules {
    type              = "AZURE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["AZURE_TO_PG", "AZURE_TO_SERVICE"]
    value_format      = "Solution-A"
    conditions {
      indexed_name {
        # negate = false
        operator = "CONTAINS"
        value    = "sa-"
      }
      key {
        type      = "STATIC"
        attribute = "AZURE_SUBSCRIPTION_NAME"
      }
    }
  }
  rules {
    type              = "SERVICE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["SERVICE_TO_HOST_LIKE", "SERVICE_TO_PROCESS_GROUP_LIKE"]
    value_format      = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_DATABASE_HOST_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "CONTAINS"
        value    = "sb-sql"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "ext1|ext2|ext3|ext4|ext5|ext6|ext7|ext8"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-B"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "ext9"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "ext10|ext11|ext12|ext13|ext14|ext15|ext16|ext17"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "ext18|ext19|ext20"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_DATABASE_HOST_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "db4|^db5|db6|db7|db8|db9"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_DATABASE_NAME"
      }
      string {
        # case_sensitive = false
        negate   = true
        operator = "REGEX_MATCHES"
        value    = "db10|db11|db12"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TOPOLOGY"
      }
      service_topology {
        # negate = false
        operator = "EQUALS"
        value    = "EXTERNAL_SERVICE"
      }
    }
  }
  rules {
    type          = "SERVICE"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "app11|app12"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TYPE"
      }
      service_type {
        # negate = false
        operator = "EQUALS"
        value    = "WEB_REQUEST_SERVICE"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TECHNOLOGY"
      }
      tech {
        # negate = false
        operator = "EQUALS"
        value {
          type = "NGINX"
        }
      }
    }
  }
  rules {
    type              = "SERVICE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["SERVICE_TO_PROCESS_GROUP_LIKE"]
    value_format      = "Solution-C"
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_NAME"
      }
      string {
        # case_sensitive = false
        negate   = true
        operator = "REGEX_MATCHES"
        value    = "app11|app12"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TYPE"
      }
      service_type {
        # negate = false
        operator = "EQUALS"
        value    = "WEB_REQUEST_SERVICE"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "SERVICE_TECHNOLOGY"
      }
      tech {
        # negate = false
        operator = "EQUALS"
        value {
          type = "NGINX"
        }
      }
    }
  }
  rules {
    type          = "HOST"
    enabled       = true
    normalization = "LEAVE_TEXT_AS_IS"
    value_format  = "Solution-D"
    conditions {
      key {
        type      = "STATIC"
        attribute = "KUBERNETES_NODE_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "EXISTS"
      }
    }
  }
  rules {
    type              = "SERVICE"
    enabled           = true
    normalization     = "LEAVE_TEXT_AS_IS"
    propagation_types = ["SERVICE_TO_HOST_LIKE", "SERVICE_TO_PROCESS_GROUP_LIKE"]
    value_format      = "Solution-A"
    conditions {
      key {
        type      = "STATIC"
        attribute = "HOST_NAME"
      }
      string {
        # case_sensitive = false
        # negate = false
        operator = "REGEX_MATCHES"
        value    = "domain1|domain2|domain3|domain4"
      }
    }
    conditions {
      key {
        type      = "STATIC"
        attribute = "KUBERNETES_NODE_NAME"
      }
      string {
        # case_sensitive = false
        negate   = true
        operator = "EXISTS"
      }
    }
  }
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-12 07:36
We will

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-12 07:37
We will look at that once again - using the sample you've provided. Hoping to resolve that once and for all with the next release.

**Comment by gmichels** [comment] 2022-10-12 16:29
I can open a ticket with support and add the verbatim HCL file. Please let me know what I should put in the ticket, to ensure it reaches you guys.

**Comment by kishikawa12** [comment] 2022-10-12 17:02
Sounds good, if you can put `@Ishikawa, Kodai` and `@Pilz, Reinhard` somewhere in the content it should get routed to us.

**Comment by gmichels** [comment] 2022-10-12 20:11
@kishikawa12 thanks, raised support request 81426. Verbatim file is attached to there.

**Comment by kishikawa12** [comment] 2022-10-13 14:14
@gmichels Thank you for the file. 

I ran the file in my local environment and did an export via the utility. The ordering of the rules that was returned was slightly different than what was in the original file. The original file would trigger changes with an unmodified HCL, the one I re-exported would return no changes needed. I asked our support team to attach the HCL that I generated based off of my export for reference.

Are you able to confirm the version and do a fresh export via the utility? Note that any small change could trigger a reorder of the list which would require another export.

Thanks!

**Comment by gmichels** [comment] 2022-10-13 16:00
@kishikawa12 for completeness, here is what I've originally done (prior to finding this issue and commenting here):

1. I had all tags already set up in the environment
2. Exported via utility (version 1.13.0)
3. Performed an apply, which said there would be changes, cancelled it
4. Renamed the existing "Solution" tag to "Solution-old"
5. Performed an apply, which created the now-new "Solution" tag
6. Performed an apply again, which said there would be changes, cancelled it

Any subsequent apply operations would yield changes, for which I had them applied every now and then, as I was also working on some other resource types. That's when I started researching for existing issues and found it here.

I attempted what you asked.

1. Re-exported via utility (again using 1.13.0)
2. Performed an apply, it said no changes are necessary

I still think there is a bug somewhere since steps 5 and 6 above were technically net-new and shouldn't have triggered changes to subsequent apply operations.

**Comment by kishikawa12** [comment] 2022-10-13 16:09
@gmichels We appreciate the detailed reply - I'll sync with @Dynatrace-Reinhard-Pilz and review the code. Thanks!

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-17 11:23
Hello @gmichels ,

After reviewing our code I've indeed identified a potential flaw in there.
The upcoming release (either today or tomorrow) will contain a reimplementation of predictably ordering the Auto Tag rules and the Conditions within.

Long term solution here will be to ensure that the order for AutoTag Rules doesn't require a specific order anymore. That will take a bit of time.

Until then we will leave this ticket open. We're hoping for feedback about the current ordering from you once the new release has been pushed out.

**Comment by gmichels** [comment] 2022-10-17 13:39
@Dynatrace-Reinhard-Pilz thanks for looking into this.

Updated the provider and attempted the following:

1. Performed a fresh export using 1.14.0
2. Grabbed the contents of the `Solution-old` autotag (which was my original manually added one, years ago)
3. Renamed the exported autotag resource to match the one existing in state (`Solution`)
4. Performed an apply, no changes were needed

Seems fixed to me.

**Comment by gmichels** [comment] 2022-10-18 15:53
@Dynatrace-Reinhard-Pilz sorry, seems like there are still issues. Today I tried adding a new rule to the bottom of the HCL file, and I am facing the same issue again.

1) apply without the new rule, confirm no changes are necessary
2) add a new `rules` block at the end of an existing `dynatrace_autotag` and apply, it gets created as expected
3) perform another apply without any changes, it wants to change the order of existing rules

I added another HCL to the support ticket (inline, not attachment, since it's rather small), for you to try it out. The `rules` block I am adding is the last one there.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-19 08:13
Hello @gmichels 

With the current version a reordering is unfortunately to be expected.

What's happening here is the following:
* The Dynatrace REST API delivers the rules in a completely unpredictable order.
* Terraform - because the rules are specified within the Schema as a List - insists that the order remains predictable.
* Our Provider therefore, whenever it receives the unordered list from the REST API, orders the rules (based on their JSON string representation).
* That order is, of course, very likely different from the order specified within your .tf file.
* As long as you don't adjust the order within your .tf file, Terraform will notice that as a difference.

If you add yet another rule at the end of an existing AutoTag, the initial apply will certainly work (the REST API doesn't care about the order).
But once the Provider is required to fetch the rules afterwards, the reordering mechanism kicks in again. Your newly added rule is likely not anymore the last one in the list then. You will be required to adjust your .tf file and insert the new rule at the correct position.

Again, that current behavior is indeed very inconvenient, and we know about it.
Our eventual goal is to change the schema in a way, that Terraform doesn't insist on a specific order anymore. We just couldn't make that happen until the last release - it's quite a lot of effort.

Makes sense?

**Comment by gmichels** [comment] 2022-10-19 22:22
@Dynatrace-Reinhard-Pilz yes it makes perfect sense, but as you already stated, renders this resource somewhat useless as it requires you to keep micro-managing the rule order.

I understand a permanent fix is upcoming and will await until it's done.

Thanks for the assistance and the provider, loving it.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-24 13:34
Hello @gmichels

With [Release 1.14.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.14.1) the rules within Auto Tags are no longer an ordered list.

That change DOES come with a price. Any changes within one of the rules will create a plan that LOOKS like all the existing rules will be removed and then replaced with other ones that have the same content. That's because of a rather poor handling for unordered sub-resources within Terraform. That behavior wont affect how the REST API is getting addressed.

Let me know if that change works for you.

**Comment by gmichels** [comment] 2022-10-24 20:37
@Dynatrace-Reinhard-Pilz just tested with 1.14.1 and I can confirm the behavior you mentioned. However, not all existing rules were showing as being removed/re-added upon a new tag rule addition, just a couple of them.

It surely looks odd seeing the plan highlighting moot changes, but at least it's consistent and subsequent plans show no changes. Not sure if you still have any future improvements to make on the provider, but at this point this behavior is much better, although of course not perfect.

Note: I was working with management zones today and noticed the exact same ordering issue happens on that resource.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-25 08:42
You're right, Management Zones as a matter of fact depend on the same rules - and we were considering to make the same changes here. But we wanted to get feedback from Auto Tagging before that.

The rather odd behavior is unfortunately the tradeoff in such cases - it's how Terraform apparently handles unordered lists of subresources. At least when using the Plugin SDK. 
Hashicorp also offers the new Plugin Framework meanwhile, which is supposed to provide better control over unordered lists. Moving to that Framework will however have to wait until further notice - it would be a complete re-implementation.

I'm closing this ticket - feel free to re-open if any further issues emerge.

**Closed by Dynatrace-Reinhard-Pilz** 2022-10-25 08:42 UTC
