### ISSUE TITLE
Cryptic error message when attempting to create a Guardian via dynatrace_generic_setting

### ISSUE THREAD

**Issue by mattBaumBeneva** [dynatrace-oss/terraform-provider-dynatrace#340] opened 2023-10-12 20:17 UTC
**Describe the bug**
We are attempting to create Site Reliability Guardians via the dynatrace_generic_setting resource with the following sample code:

```
resource "dynatrace_generic_setting" "test" {
  schema = "app:dynatrace.site.reliability.guardian:guardians"
  scope  = "environment"
  value = jsonencode({
    "name" : "appli_3",
    "tags" : [
      "application:EasyTravel"
    ],
    "objectives" : [
      {
        "name" : "appli3",
        "description" : "guardian lab test",
        "objectiveType" : "REFERENCE_SLO",
        "referenceSlo" : "func:slo.my_new_real_user_experience_objective",
        "comparisonOperator" : "GREATER_THAN_OR_EQUAL",
        "target" : 10.0,
        "warning" : 20.0
      }
    ]
  })
}
```

The following cryptic error message (indicating a HTTP return code of "0") appears in our logs:

```
14:32:25  │ Error: status code 0 (expected: 200): 
14:32:25  │ 
14:32:25  │   with dynatrace_generic_setting.test,
14:32:25  │   on APP_easyt.tf line 16, in resource "dynatrace_generic_setting" "test":
14:32:25  │   16: resource "dynatrace_generic_setting" "test" {
14:32:25  │ 
```

**To Reproduce**
1. Apply the above code
2. See error

**Expected behavior**
The resource should be successfully applied or fail with a clear message indicating the cause of the failure.

**Additional context**
Provider version 1.44.0

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-16 08:27
Hello @mattBaumBeneva,

The origin of the error message you're getting stems from the fact, that you're trying to configure settings that require an OAuth Client in order to get accepted by the REST API. It's explained (although that note definitely needs some improvement) [here](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/generic_setting).

So, on short notice, in order for your resource to get accepted by the REST API, you need to navigate to "Account Management" and create an OAuth Client with at least the permissions `settings:objects:write` and `app-engine:apps:run`.
To configuring the Terraform Provider with this OAuth Client you can utilize the environment variables `DYNATRACE_AUTOMATION_CLIENT_ID` and `DYNATRACE_AUTOMATION_CLIENT_SECRET` (alternatively also `DT_CLIENT_ID` and `DT_CLIENT_SECRET` will be accepted.

A bit of background here: In order for you settings to get passed along to the Dynatrace App the Dynatrace Server actually needs to invoke portions of that specific App. That requires a scope that cannot get simply assumed by an API Token - but an OAuth Client can.

The error message is getting improved with the next release.

**Comment by mattBaumBeneva** [comment] 2023-10-16 12:49
We had already completed that configuration as indicated in the documentation when we produced the error, but we will double check to make sure we didn't make a mistake.

**Comment by mattBaumBeneva** [comment] 2023-10-16 15:49
@Dynatrace-Reinhard-Pilz , I have verified our configuration.
I printed our environment variables (using printenv) and both variables are passed correctly, just like we already declare the variables for the API token and the tenant.
Here is a sample from our Jenkins log (values modified for security purposes):

11:31:23  DYNATRACE_AUTOMATION_CLIENT_ID=dt0s02.NRPULXVB
11:31:23  DYNATRACE_AUTOMATION_CLIENT_SECRET=dt0s02.NRPULXVB.E76EBO77WU4KY6YNWX2K5XKFYMVQFRAVMT5ZBXADSOGBUJPZHGD2KJIT3HWBBGYB

In that same run, we obtained the error (return code 0).

I have successfully POSTed a Guradian via the REST API with Postman by completing the OAuth 2.0 authentication flow.
Is there also an environment variable we need to pass with the environment URN (as we do when calling the /token service), or does the Provider handle this internally?

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-17 10:38
Matt, what are you getting back when running 

```
curl --location 'https://sso.dynatrace.com/sso/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=dt0s02.########' \
--data-urlencode 'client_secret=dt0s02.########.################################################################' \
--data-urlencode 'grant_type=client_credentials'
```

in a Linux shell?

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-17 10:42
Just for clarification, this the kind of request the OAuth Client of Golang sends out for getting the Bearer Token. The response SHOULD look like this:

```
{
    "scope": "settings:objects:write app-engine:apps:run",
    "token_type": "Bearer",
    "expires_in": 300,
    "access_token": "##########################",
    "resource": "urn:dtaccount:########-####-####-####-############"
}
```

The `scope` may contain more entries than in my example, but `settings:object:write` and `app-engine:apps:run` are a requirement for the Settings API to accept the request.

**Comment by mattBaumBeneva** [comment] 2023-10-17 12:36
Hi, @Dynatrace-Reinhard-Pilz .

The command:

`curl --insecure --location 'https://sso.dynatrace.com/sso/oauth2/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=dt0s02.NRPULXVB' --data-urlencode 'client_secret=dt0s02.NRPULXVB.E76EBO77WU4KY6YNWX2K5XKFYMVQFRAVMT5ZBXADSOGBUJPZHGD2KJIT3HWBBGYB' --data-urlencode 'grant_type=client_credentials'
`
Response:
  
```
{
"scope":"app-engine:apps:run settings:objects:write settings:objects:read settings:schemas:read",
"token_type":"Bearer",
"expires_in":300,
"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IjEifQ.eyJzdWIiOiIwYjU4ZDg2ZC0wZjlkLTRjNjUtODc4OC02MWY2YjZhZWQ5ODciLCJyZXMiOiJ1cm46ZHRhY2NvdW50OjY4OThlZDcxLTYyMzUtNDY1NC1iNGYwLTY1MGQ5YTg4N2U1MCIsIl9jbGFpbV9uYW1lcyI6eyJncm91cHMiOiIwIn0sInByZWZlcnJlZF91c2VybmFtZSI6Im1hdHRoZXcuYmF1bUBiZW5ldmEuY2EiLCJndCI6ImNjIiwiaW50IjpmYWxzZSwiYXVkIjoiZHQwczAyLk5SUFVMWFZCIiwic2NvcGUiOiJhcHAtZW5naW5lOmFwcHM6cnVuIHNldHRpbmdzOm9iamVjdHM6d3JpdGUgc2V0dGluZ3M6b2JqZWN0czpyZWFkIHNldHRpbmdzOnNjaGVtYXM6cmVhZCIsIl9jbGFpbV9zb3VyY2VzIjp7IjAiOnsiZW5kcG9pbnQiOm51bGx9fSwiZXhwIjoxNjk3NTQ2MjY0LCJpYXQiOjE2OTc1NDU5NjQsImp0aSI6IjAwMjM3MmY0LWI3NzgtNGQxMS1hYTdiLTAyOWIzZmIwYmRhMCIsImVtYWlsIjoibWF0dGhldy5iYXVtQGJlbmV2YS5jYSJ9.u_w0PkyCMdNEvzONSzhZ1PABosSL6-CwAmqzPoWSoRuYhLTnGDClknsCS6aEX1rTAkmocptQH41LIXJZu1ZovA",
"resource":"urn:dtaccount:6898ed71-6235-4654-b4f0-650d9a887e50"
}
```

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-17 13:59
Matt, I'm afraid I need to ask for patience until we can push out another release. The current version of the provider isn't able to log out the OAuth Client communication. I'm planning to release a v1.44.1 still this week, where I've added functionality for that.

Once v1.44.1 is released, please apply the generic setting with the following environment variables defined:
```
DYNATRACE_ENV_URL=***
DYNATRACE_API_TOKEN=***
DYNATRACE_AUTOMATION_CLIENT_ID=***
DYNATRACE_AUTOMATION_CLIENT_SECRET=***

DYNATRACE_DEBUG=true
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
DYNATRACE_DEBUG_GENERIC_SETTINGS=true
```

* `DYNATRACE_DEBUG`, `DYNATRACE_LOG_HTTP` and `DYNATRACE_HTTP_RESPONSE` ensure that HTTP traffic is getting logged into a file named `terraform-provider-dynatrace.http.log`
* `DYNATRACE_DEBUG_GENERIC_SETTINGS` will ensure that also the OAuth Communication is getting intercepted

Be aware of the fact, that the log file will contain client secret and token in plain text.

**Comment by kishikawa12** [comment] 2023-10-18 15:59
Hi @mattBaumBeneva,

[Release v1.44.1](https://github.com/dynatrace-oss/terraform-provider-dynatrace/releases/tag/v1.44.1) is now available, thanks!

**Comment by mattBaumBeneva** [comment] 2023-10-18 18:38
I can confirm we now see the much clearr error message:
`14:31:07  │ Error: An OAuth Client is required for creating these settings. The configured credentials are currently based on API Tokens only. More information: https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/generic_setting`

I will recover the log you requested.

**Comment by mattBaumBeneva** [comment] 2023-10-18 18:43
I am including the relevant section of the log. Please ignore leading timestamps from our Jenkins log. I had to "cat" the file, as I cannot access the worker node directly. I also modified sensitive fields.

```
14:31:07  2023/10/18 18:29:15   => [{"code":400,"error":{"code":400,"message":"No OAuth token provided"},"invalidValue":{"name":"appli_3","objectives":[{"comparisonOperator":"GREATER_THAN_OR_EQUAL","description":"guardian lab test","name":"appli3","objectiveType":"REFERENCE_SLO","referenceSlo":"func:slo.my_new_real_user_experience_objective","target":10,"warning":20}],"tags":["application:EasyTravel"]}}]
14:31:07  2023/10/18 18:29:15 400 [{"code":400,"error":{"code":400,"message":"No OAuth token provided"},"invalidValue":{"name":"appli_3","objectives":[{"comparisonOperator":"GREATER_THAN_OR_EQUAL","description":"guardian lab test","name":"appli3","objectiveType":"REFERENCE_SLO","referenceSlo":"func:slo.my_new_real_user_experience_objective","target":10,"warning":20}],"tags":["application:EasyTravel"]}}]
14:31:07  2023/10/18 18:29:15 POST https://xcz80425.live.dynatrace.com/api/v2/settings/objects
14:31:07      [{"schemaId":"app:dynatrace.site.reliability.guardian:guardians","scope":"environment","value":{"name":"appli_3","objectives":[{"comparisonOperator":"GREATER_THAN_OR_EQUAL","description":"guardian lab test","name":"appli3","objectiveType":"REFERENCE_SLO","referenceSlo":"func:slo.my_new_real_user_experience_objective","target":10,"warning":20}],"tags":["application:EasyTravel"]}}]
14:31:07  2023/10/18 18:29:15 POST https://sso.dynatrace.com/sso/oauth2/token
14:31:07  2023/10/18 18:29:15    client_id=dt0s02.XXXXXXXX&client_secret=dt0s02.XXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&grant_type=client_credentials
14:31:07  2023/10/18 18:29:15 GET https://xcz80425.live.dynatrace.com/api/v2/settings/objects?schemaIds=builtin%3Alogmonitoring.log-events&fields=objectId%2Cvalue%2Cscope%2CschemaVersion&pageSize=100
14:31:07  2023/10/18 18:29:15 200 OK [{"code":200,"objectId":"vu9U3hXa3q0AAAABACRidWlsdGluOmFub21hbHktZGV0ZWN0aW9uLmRpc2stcnVsZXMACkhPU1RfR1JPVVAAEDY2RTg2NTFCQzJCNkREOUUAJGNlMzAwNTY0LTFmYjEtMzI2My1iMGQ2LTA0ZjAwNmQzNTZkML7vVN4V2t6t"}]
```

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-19 14:15
Excellent! I'm glad we found the root cause in your case.

Agreed, we will find a way to distinguish between missing/wrong oauth credentials and connection issues. As much as I hate it, I will have to mess around with my personal firewall in order to reproduce that behavior :-)

If it's ok for you, I'd like to keep this ticket open until then - I'd be grateful if you could validate that proper error messages are getting delivered using your Jenkins workers.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-10-19 14:26
One additional question, Matt:
When you're executing the curl command on your Jenkins workers, what's the output of curl in that case? Is the connection timing out? Or are you getting at least a status code back?

**Comment by mattBaumBeneva** [comment] 2023-10-19 14:29
In my case, we get a Connection Reset (no HTTP status code). Which is probably why the initial unclear message listed a code of zero (0).

`09:19:07  curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sso.dynatrace.com:443`

**Comment by mattBaumBeneva** [comment] 2023-10-20 19:42
I can confirm that we successfully created the generic setting object once our firewall rules were modified.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2024-03-07 10:04
Hello Matt, I'm closing this ticket, since your actual issue already has been identified.
We've also made improvements that should allow us to identify the root cause for similar situations easier next time.

**Closed by Dynatrace-Reinhard-Pilz** 2024-03-07 10:04 UTC
Labels: bug
