### ISSUE TITLE
"BROWSER_EXTENSION_INJECTED" web application configurations did not apply

### ISSUE THREAD

**Issue by cyang1001** [dynatrace-oss/terraform-provider-dynatrace#196] opened 2023-02-10 21:21 UTC
**Describe the bug**
I was trying to use the `dynatrace_web_application` to create a "browser-extension-injected" web application. However, the configurations related to the"monitoring settings", "data privacy", and "error rules" did not apply to the cluster. For example, I have the below block for `javascript_framework_support` in my code, however, it was not reflected on WebUI. Also, when I export the configurations again, I will get two configuration files, one shows the same configuration as I had in my code, and the other shows what I can see on the UI.

_Code I applied:_ 
```
javascript_framework_support {
      # active_x_object = false 
      # angular = false 
      # dojo = false 
      # extjs = false 
      # icefaces = false 
      jquery = true 
      # moo_tools = false 
      # prototype = false 
    }
```
as well as: 
```
fetch_requests = true
xml_http_request = true
```

_Code I exported using export utility:_
File 1: xxx.web_application.tf
```
javascript_framework_support {
      active_x_object = false
      angular         = false
      dojo            = false
      extjs           = false
      icefaces        = false
      jquery          = true
      moo_tools       = false
      prototype       = false
    }

```
```
fetch_requests = true
xml_http_request = true
```

File 2: xxx_1.web_application.tf
```
Javascript_framework_support {
      active_x_object = false
      angular         = false
      dojo            = false
      extjs           = false
      icefaces        = false
      jquery          = false
      moo_tools       = false
      prototype       = false
    }
```
```
fetch_requests = false
xml_http_request = false
```

**To Reproduce**
1. create a web app with default values except the block above, can also create data privacy and error rules for this app
2. check the UI
3. export the configurations

**Expected behavior**
The configurations mentioned above for browser-extension-injected applications can be applied.

**Additional context**
- Dynatrace managed cluster version: 1.256
- Provider version: 1.19.0 (it didn't work in 1.14.1 either)

**Comment by cyang1001** [comment] 2023-02-14 17:46
@kishikawa12 Hi Kodai, thanks for the response! We also find that the API-created "browser-extension-injected" application could not capture all user actions. In our case, ours is able to capture some user actions but not all of them. 
Thanks.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-02-24 10:47
Hello @cyang1001 ,
I have an update for the initial issue you've reported. As @kishikawa12 mentioned, the root cause is that a duplication application is getting created when trying to update it. That bug is planned to get fixed with version 1.261 of the Dynatrace Cluster. 

Regarding your second question: You're observing not all user actions being captured ONLY when you're maintaining that WebApp via REST API? If you're configuring it via WebUI everything is getting captured?

**Comment by cyang1001** [comment] 2023-02-24 16:45
Hi @Dynatrace-Reinhard-Pilz , thanks for the update! I also just noticed that since it was the duplication showing up on WebUI, we are unable to really delete or modify the configuration we created via the provider! Do you have any idea to clean up the configurations?

For intermittent user actions, it was the one created by REST API...

**Comment by cyang1001** [comment] 2023-02-27 16:53
Hi, just want to add another issue: even though the web applications created for manually-injected apps work (can capture user actions), the autotags related to the "web application name pattern" cannot apply to those apps. Is this reasonable behaviour? Could you please also see if you can replicate this issue?

**Comment by kishikawa12** [comment] 2023-08-08 19:51
Hi @cyang1001,

Looks like this ticket fell through the cracks as the initial issue was resolved. I'm unsure if you are still experiencing any of the other issues you commented, but I've tried to address some of your follow-ups. 

Unfortunately the duplicate applications that were created will need to be manually deleted. Regarding the automatic tag question, I was able to successfully apply it to a manually-injected app with the `Web application name` property.

I'll close this since the issue related to the ticket is resolved. Please feel free to create a new GitHub issue for Terraform related issues. For general product support, I recommend to utilize the chat feature available in the Dynatrace UI for a quicker response.

Thanks!

**Closed by kishikawa12** 2023-08-08 19:51 UTC
Labels: bug
