### ISSUE TITLE
[Error] Exporting SLOs Using the Terraform Binary Not Working

### ISSUE THREAD

**Issue by rafikt1992** [dynatrace-oss/terraform-provider-dynatrace#165] opened 2022-12-09 15:44 UTC
**Describe the bug**
Exporting the DT SLOs isn't possible using the Terraform Binary
**To Reproduce**

1. get the terraform provider terraform init
2. run ``` ./.terraform/plugins/registry.terraform.io/dynatrace-oss/dynatrace/1.14.1/darwin_amd64/terraform-provider-dynatrace_v1.14.1 export dynatrace_slo```
3. i get the following error 
```
The environment variable DYNATRACE_TARGET_FOLDER has not been set - using folder 'configuration' as default
Bad Request (GET) [our DT URL]/e/8e9e0861-8dc5-4d0f-b38b-0f55da50409b/api/v2/slo?sloSelector=id("f64ee760-49f6-3c81-b447-2334e539597f")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false
```
**Expected behavior**
i get the HCL files for the SLOs

**Screenshots**
error above

**Desktop (please complete the following information):**
 - OS: MAC OS Ventura M1 Silicon
 -  terraform version = "1.14.1"

**Additional context**
this is also happening for anomalyDetection 
```
Internal Server Error (GET) https://our-url/e/e4eb8d9f-d239-4ee5-bb6a-470a8c277dff/api/config/v1/anomalyDetection/metricEvents/ruxit.perfmon.dotnetV4%3A%25TimeInGC%3Atime_in_gc_alert_high_generic
```
but not for
1. autotags
2. dashboards
3. management zones
4. alert_profiles

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-12-12 13:05
Hello @rafikt1992 ,

Is it possible that there's some sort of firewall in between your workstation and the Dynatrace Cluster?
Reason for the question is, that the format of the errors looks suspiciously like they are coming from another component than the REST API of Dynatrace.

```
Bad Request (GET) [our DT URL]/e/8e9e0861-8dc5-4d0f-b38b-0f55da50409b/api/v2/slo?sloSelector=id("f64ee760-49f6-3c81-b447-2334e539597f")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false
```

The REST API would respond - even for Bad Request - with JSON Payload.

I also tested out your example about custom anomalies:

```Internal Server Error (GET) https://our-url/e/e4eb8d9f-d239-4ee5-bb6a-470a8c277dff/api/config/v1/anomalyDetection/metricEvents/ruxit.perfmon.dotnetV4%3A%25TimeInGC%3Atime_in_gc_alert_high_generic
```

That exact link (I just included a query parameter `Api-Token` for authentication) works even via Browser when sent against a random environment.

So, what I suspect here is, that something sits in the middle between your workstation and the server and tries to interpret the URLs. 

Your thoughts?

**Comment by rafikt1992** [comment] 2022-12-13 13:48
i have manually attempted to create the slo HCL file as following

```JSON
resource "dynatrace_slo" "AI_API_Failure_rate_5xx_Terraform" {
  name = "AI API - Failure rate (5xx) Terraform"
  evaluation = "AGGREGATE"
  target = 99.97
  timeframe = "-1w"
  warning = 99.98
  disabled = false
  description = "% of requests without 5xx in AI API - Terraform"
  metric_expression = "(100)*((calc:service.slo_aiapi_notfailedrequestcount:splitBy())/(calc:service.slo_aiapi_allrequestcount:splitBy()))"
  # denominator = 0
  # numerator = 0
}
```

Applying the above resulted in a similar error

```
 Error: Bad Request (GET) https://sample.com/e/8e9e0861-8dc5-4d0f-b38b-0f55da50409b/api/v2/slo?sloSelector=id("39000128-f9dd-3719-83a1-a8280028c364")&pageSize=10000&sort=name&timeFrame=CURRENT&pageIdx=1&demo=false&evaluate=false
│ 
```

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-01-31 09:36
Hello @rafikt1992 
If you're still having the same issues with v1.18.1, could you please set the following environment variable before running an export / executing `terraform apply`:

```
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
```

The log file is of course of your choosing. In case an error happens during one of the requests, you should expect to also find a file `terraform-provider-dynatrace.http.err.log`.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-02-24 12:27
Hello @rafikt1992 
Following up on this issue. Are you experiencing the same issues using a version of the terraform provider > v1.18.1?

**Comment by ivy67941842** [comment] 2023-03-16 02:50
I'm experiencing the same issue(bad request) when creating slo resource but actually the slo is created successfully.

`Error: status code 400 (expected: [200]): <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>`

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-03-16 08:00
Hello @aakdjkf ,

Please run a sample that's creating an SLO with these environment variables:
```
DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log
DYNATRACE_HTTP_RESPONSE=true
```
That should produce the files `terraform-provider-dynatrace.http.log` and `terraform-provider-dynatrace.http.err.log` within your working directory.
It would give me insight into which request exactly fails and for what reason.

What version is your Dynatrace Cluster currently running on?

**Comment by v94401** [comment] 2023-03-16 12:59
Hello,

I can confirm @aakdjkf problem with dynatrace provider 1.22.0. SLO is created but we got the same error:

`Error: status code 400 (expected: [200]): <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>`

@Dynatrace-Reinhard-Pilz I tested your proposal but both files are empty.

**Comment by v94401** [comment] 2023-03-17 07:50
I enabled terraform logs and this is the output:

`2023-03-17T09:42:18.866+0200 [TRACE] checkPlannedChange: Verifying that actual change (action Create) matches planned change (action Create)
dynatrace_slo.XSUAA_Traffic_SLO: Creating...
2023-03-17T09:42:18.867+0200 [INFO]  Starting apply for dynatrace_slo.XSUAA_Traffic_SLO
2023-03-17T09:42:18.867+0200 [DEBUG] dynatrace_slo.XSUAA_Traffic_SLO: applying the planned Create change
2023-03-17T09:42:18.867+0200 [TRACE] GRPCProvider: ApplyResourceChange
2023-03-17T09:42:18.867+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Received request: tf_resource_type=dynatrace_slo tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:805 @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider timestamp=2023-03-17T09:42:18.867+0200
2023-03-17T09:42:18.867+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Sending request downstream: tf_resource_type=dynatrace_slo @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tf5serverlogging/downstream_request.go:17 tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider tf_rpc=ApplyResourceChange timestamp=2023-03-17T09:42:18.867+0200
2023-03-17T09:42:18.867+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Calling downstream: @module=sdk.helper_schema tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 tf_provider_addr=provider tf_resource_type=dynatrace_slo tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:836 timestamp=2023-03-17T09:42:18.867+0200
2023-03-17T09:42:19.258+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Called downstream: tf_resource_type=dynatrace_slo tf_provider_addr=provider tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:838 @module=sdk.helper_schema timestamp=2023-03-17T09:42:19.258+0200
2023-03-17T09:42:19.258+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Received downstream response: @module=sdk.proto tf_proto_version=5.3 tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 tf_rpc=ApplyResourceChange diagnostic_warning_count=0 tf_provider_addr=provider tf_req_duration_ms=390 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tf5serverlogging/downstream_request.go:37 diagnostic_error_count=1 tf_resource_type=dynatrace_slo timestamp=2023-03-17T09:42:19.258+0200
2023-03-17T09:42:19.258+0200 [ERROR] provider.terraform-provider-dynatrace_v1.23.0: Response contains error diagnostic: @module=sdk.proto diagnostic_detail= diagnostic_summary="status code 400 (expected: [200]): <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>" tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_resource_type=dynatrace_slo tf_rpc=ApplyResourceChange timestamp=2023-03-17T09:42:19.258+0200
2023-03-17T09:42:19.259+0200 [TRACE] provider.terraform-provider-dynatrace_v1.23.0: Served request: @module=sdk.proto tf_provider_addr=provider tf_req_id=5faecf85-3784-900e-03d0-13616d9e1852 tf_resource_type=dynatrace_slo tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:831 tf_proto_version=5.3 timestamp=2023-03-17T09:42:19.258+0200
2023-03-17T09:42:19.260+0200 [TRACE] maybeTainted: dynatrace_slo.XSUAA_Traffic_SLO encountered an error during creation, so it is now marked as tainted
2023-03-17T09:42:19.261+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for dynatrace_slo.XSUAA_Traffic_SLO
2023-03-17T09:42:19.261+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for dynatrace_slo.XSUAA_Traffic_SLO
2023-03-17T09:42:19.261+0200 [TRACE] evalApplyProvisioners: dynatrace_slo.XSUAA_Traffic_SLO is tainted, so skipping provisioning
2023-03-17T09:42:19.261+0200 [TRACE] maybeTainted: dynatrace_slo.XSUAA_Traffic_SLO was already tainted, so nothing to do
2023-03-17T09:42:19.261+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for dynatrace_slo.XSUAA_Traffic_SLO
2023-03-17T09:42:19.261+0200 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: removing state object for dynatrace_slo.XSUAA_Traffic_SLO
2023-03-17T09:42:19.262+0200 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2023-03-17T09:42:19.263+0200 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2023-03-17T09:42:19.263+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2023-03-17T09:42:19.271+0200 [ERROR] vertex "dynatrace_slo.XSUAA_Traffic_SLO" error: status code 400 (expected: [200]): <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
2023-03-17T09:42:19.271+0200 [TRACE] vertex "dynatrace_slo.XSUAA_Traffic_SLO": visit complete, with errors
2023-03-17T09:42:19.271+0200 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"] (close)" errored, so skipping
2023-03-17T09:42:19.271+0200 [TRACE] dag/walk: upstream of "root" errored, so skipping
2023-03-17T09:42:19.271+0200 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2023-03-17T09:42:19.273+0200 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2023-03-17T09:42:19.273+0200 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate`

**Comment by v94401** [comment] 2023-03-17 07:51
Forgot to mention that it is tested with dynatrace-provider - 1.22 and 1.23.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-03-17 11:38
Hello @v94401 ,

I'm looking at the HTML code of the error page you're getting

```
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```
That HTML code is definitely not getting produced by the Dynatrace REST API. Especially `background-color:#525D76` looks suspiciously like either Apache HTTP Server or Apache Tomcat. Is there any chance that the host executing terraform needs to go through a load balancer or something similar?

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-03-17 12:34
Hello everyone,

What's apparently common to everyone here, who experiences issues with SLOs is the fact, that calls to the REST API are not being made directly, but have to go through another server. As a result, responses with error status may get repackaged as error pages.
The Terraform Provider performs a couple of additional steps after applying a SLO - it actually polls for the just applied SLO multiple times in order to ensure it's known to every cluster node. Unfortunately that's not guaranteed by the REST API right away. It can take up to a minute or longer until the whole cluster knows about the existence of the SLO.

These two facts combined can lead to the situation that the provider - while polling - doesn't receive the error messages it expects to happen temporarily.

For the next release I've included a couple of changes that MAY solve that problem. I unfortunately cannot reproduce your issues locally, so I would have to ask for your help, once we've released these changes.

**Comment by csy2018** [comment] 2023-03-24 03:35
I have noticed that some fixes have been made, but they do not appear to be complete. I have submitted a pull request regarding this issue. Could you kindly review it? Thank you.
https://github.com/dynatrace-oss/terraform-provider-dynatrace/pull/219

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-07-14 10:24
I'm closing this ticket, assuming that the contribution from @csy2018 has taken care of it. Please drop us a message, in case you still experience problems and we will re-open the ticket.

**Closed by Dynatrace-Reinhard-Pilz** 2023-07-14 10:24 UTC
Labels: bug
