### ISSUE TITLE
Panic when creating a SLO

### ISSUE THREAD

**Issue by alsofr** [dynatrace-oss/terraform-provider-dynatrace#237] opened 2023-04-21 13:13 UTC
**Describe the bug**
When creating an SLO, the terraform apply phase throws a panic

**To Reproduce**
1. Configure a terraform provider with url and token
2. Create an SLO definition as below
   ```
    resource "dynatrace_slo" "service-availability-slo" {
      name              = "service-availability-slo"
      evaluation        = "AGGREGATE"
      filter            = "type(\"SERVICE\")"
      metric_expression = "calc:availability.service:splitBy()"
      target            = 99.58
      timeframe         = "-5m"
      warning           = 99.99
    }
   ```
3. Run terraform apply
4. The error below is thrown
    ```
    + terraform apply -input=false --parallelism 250 --auto-approve /tmp/state.odiKxX
    dynatrace_slo.service-availability-slo: Creating...
    ╷
    │ Error: Plugin did not respond
    │ 
    │   with dynatrace_slo.service-availability-slo,
    │   on dynatrace.tf line 1, in resource "dynatrace_slo" "service-availability-slo":
    │    1: resource "dynatrace_slo" "service-availability-slo" {
    │ 
    │ The plugin encountered an error, and failed to respond to the
    │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
    │ contain more details.
    ╵
    
    Stack trace from the terraform-provider-dynatrace_v1.27.0 plugin:
    
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xab7a41]
    
    goroutine 16 [running]:
    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v2/slo.(*service).Create.func1(0x0?)
	    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v2/slo/service.go:127 +0x21
    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/rest.(*request).Raw(0xc00014aea0)
	    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/rest/request.go:222 +0x6c6
    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/rest.(*request).Finish(0xc00014aea0, {0x0, 0x0, 0xffc1a0?})
	    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/rest/request.go:146 +0xb2
    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v2/slo.(*service).Create(0xc000135540, 0xc00014dd00)
	    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/api/v2/slo/service.go:141 +0x202
    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings.(*GenericCRUDService[...]).Create(0xfd8e40?, {0x13d3e10?, 0xc00014dd00?})
	    github.com/dynatrace-oss/terraform-provider-dynatrace/dynatrace/settings/generic_crud_service.go:40 +0x3b
    github.com/dynatrace-oss/terraform-provider-dynatrace/resources.(*Generic).Create(0xc0000ac7d0, {0x13db9b0, 0xc00014ad80}, 0xc00014db80, {0xf068a0, 0xc0001da320})
	    github.com/dynatrace-oss/terraform-provider-dynatrace/resources/generic.go:101 +0x207
    github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging.Enable.func1({0x13db9b0, 0xc00014ad80}, 0x0?, {0xf068a0, 0xc0001da320})
	    github.com/dynatrace-oss/terraform-provider-dynatrace/provider/logging/logging.go:78 +0x83
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003a5960, {0x13db9e8, 0xc0008f70e0}, 0xd?, {0xf068a0, 0xc0001da320})
	    github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003a5960, {0x13db9e8, 0xc0008f70e0}, 0xc000722340, 0xc00014da00, {0xf068a0, 0xc0001da320})
	    github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000010168, {0x13db9e8?, 0xc0008f6fc0?}, 0xc0001940f0)
	    github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
    github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002da780, {0x13db9e8?, 0xc0008f65d0?}, 0xc0001498f0)
	    github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
    github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1195820?, 0xc0002da780}, {0x13db9e8, 0xc0008f65d0}, 0xc000149880, 0x0)
	    github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ce1e0, {0x13f7700, 0xc000582680}, 0xc0005b7560, 0xc000700d50, 0x1b952e0, 0x0)
	    google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc0002ce1e0, {0x13f7700, 0xc000582680}, 0xc0005b7560, 0x0)
	    google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
	    google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
	    google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
    
    Error: The terraform-provider-dynatrace_v1.27.0 plugin crashed!
    
    This is always indicative of a bug within the plugin. It would be immensely
    helpful if you could report the crash with the plugin's maintainers so that it
    can be fixed. The output above should help diagnose the issue.
    ```

**Expected behavior**
The SLO should be created or an actionable error message returned

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-04-28 10:03
Hello @alsofr ,

I cannot reproduce this error - neither with the most recent version of the provider nor with v1.27.0. Seeing `--parallelism 250` within your command line, can I assume that this SLO is just a part of a bigger module and we're dealing with an issue that just emerges at a certain load the REST API is subjected to?

I nevertheless implemented a few nil reference checks at the code location the crash trace was hinting to. Because it's at the moment unclear to me how this error can get enforced and it's therefore not certain that just this one fix gets rid of the crash, we will keep this issue open until I can get feedback from you.

We're targeting for v1.29.0 mid next week. I'd appreciate if you could recheck with that version whether the issue is gone with that version.

thanks,
Reinhard

**Comment by alsofr** [comment] 2023-05-02 07:22
Hi Reinhard, thank you for taking care of this, much appreciated.
I'll make sure to test again with the version 1.29.0 as soon as it is released. Hopefully the checks you added help me get more information out of the logs.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-05-22 12:06
Hello @alsofr, I'm closing this ticket, assuming the issue has been resolved. In case it still persists, just add a comment and I'll reopen the ticket.

**Closed by Dynatrace-Reinhard-Pilz** 2023-05-22 12:06 UTC
Labels: bug
