### ISSUE TITLE
Question: Resource IDs & generating duplicate resources on each run

### ISSUE THREAD

**Issue by smc87** [dynatrace-oss/terraform-provider-dynatrace#38] opened 2021-06-02 11:36 UTC
Hello,
After any change (e.g. change dashboard owner), a new dashboard is created rather than the existing dashboard being modified. 
The old dashboard is also left in place.

I was looking at the docs here
https://github.com/dynatrace-oss/terraform-provider-dynatrace/blob/main/docs/resources/dashboard.md

And noticed that id is defined as an optional key
![image](https://user-images.githubusercontent.com/6291983/120470304-47fc5b00-c39b-11eb-88f9-5257419fa2ca.png)

I tried using this in the hope I could get terraform to hook onto a single resource instead of creating new ones for each run but it threw the error:
"Error: Invalid or unknown key"

In my dashboard .tf file (generated via direct invocation of the tool) I added the id of the dashboard in dyntrace like this:
'''
resource "dynatrace_dashboard" "mydashboard" {
  id = "xxxx-xxxx-xxxx-xxxx-xxxxxxx"
  dashboard_metadata {
  ...
'''

Maybe I am misusing this, is there another way to prevent duplicates being created?
Many thanks.

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2021-06-02 12:14
Hi @smc87 

If I'm not mistaken you would like to share the IDs of Dashboards across multiple Dynatrace Environments, am I right?

**Comment by smc87** [comment] 2021-06-02 12:38
Hi @Dynatrace-Reinhard-Pilz 
No, just within the same environment. Apologies as this may also just be my misunderstanding as I am quite new to terraform. 

For example I have environment xxx.live.dynatrace.com and my dashboard_metadata contains an owner of "smc87"
When I run terraform apply the dashboard is created in my environment as expected.

If I then make a change to the dashboard (change the owner to "smc87-2") and run terraform apply again, then a second dashboard is created in the same environment when I would expect it to update the owner of the existing dashboard.

![image](https://user-images.githubusercontent.com/6291983/120481223-cf4fcb80-c3a7-11eb-9c1b-69d41d0dacbb.png)

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2021-06-02 13:02
Thanks for the clarification. I can actually reproduce this locally.
The bad news is that this seems to be some sort of special handling by the Dynatrace Server. Changing the owner somehow creates a copy for that specific user, but doesn't get rid of the original one. At least when sending the payload directly via REST API (circumventing terraform) I'm getting the same results.
I will have to look into that issue closer. Perhaps there is a workaround (e.g. having the terraform provider to delete the old dashboard on purpose).
Need to ask for patience until next week, though. I will keep the issue open until we've clarified whether and how this can get solved.

**Comment by smc87** [comment] 2021-06-02 13:18
Ah, If it is just special behaviour on the owner field then that is not such an issue.
This just happened to be the first thing I had tested, sods law.

Thanks for your time.

**Comment by sudhirkumar05** [comment] 2022-02-22 00:29
Dynatrace Team,
What is the update on this field, using `id` attribute in any of the terraform resource return an error
`https://github.com/dynatrace-oss/terraform-provider-dynatrace/issues/38`
code sample
```
`resource "dynatrace_http_monitor" "http_monitor" {
  name      = var.synthetic_name
  id        = var.synthetic_id
 
```
![image](https://user-images.githubusercontent.com/90434385/155042063-b5de965e-a175-4fb2-bcfe-7679ed30b445.png)

**Comment by smc87** [comment] 2022-03-09 09:12
Hi @Dynatrace-Reinhard-Pilz 
Do you think the issues with terraform & the dynatrace API will ever be resolved?

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-02-24 13:57
Hello @smc87 ,
The issue with Dashboards duplicating when changing the owner has been addressed by Dynatrace R&D last fall.
I just rechecked, both using the API directly and the Terraform Provider. Was not able to reproduce the problem anymore.

Let me know in case it behaves differently in your environment.

**Closed by Dynatrace-Reinhard-Pilz** 2023-02-24 13:57 UTC
