### ISSUE TITLE
multiple resource definition in single tf file

### ISSUE THREAD

**Issue by Karthikeyanraman94** [dynatrace-oss/terraform-provider-dynatrace#15] opened 2021-04-24 20:11 UTC
Is it meant all the resources should be maintained in separate tf file?
I tried to put multiple auto tags, management zone resource in a single tf file, and  I recieve the below error during terraform apply.. This looks to be a serious bug and an immediate fix would be more helpful

01:37:14  Error: rpc error: code = Unavailable desc = transport is closing
01:37:14  
01:37:14  
01:37:14  
01:37:14  Error: rpc error: code = Unavailable desc = transport is closing
01:37:14  
01:37:14  
01:37:14  
01:37:14  Error: rpc error: code = Unavailable desc = transport is closing
01:37:14

**Comment by Karthikeyanraman94** [comment] 2021-04-25 07:44
also if I change the terraform reference management zone resource name, it throws this error after destruction.. Looks like a retry and timewait function needs to be added

13:08:12  dynatrace_management_zone.test: Destruction complete after 1s
13:08:12  
13:08:12  Error: {
13:08:12    "code": 400,
13:08:12    "message": "Constraints violated.",
13:08:12    "constraintViolations": [
13:08:12      {
13:08:12        "parameterLocation": "PAYLOAD_BODY",
13:08:12        "location": "",
13:08:12        "message": "Management zone must have a unique name.",
13:08:12        "path": "name"
13:08:12      }
13:08:12    ]
13:08:12  }

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2021-04-26 07:11
Hi Karthikeyanraman94,

You shouldn't be required to maintain a separate .tf file per resource.
Could you share some of the .tf files you've experienced these issues with?

**Comment by Karthikeyanraman94** [comment] 2021-04-26 07:35
I dont think I can able to share it here, due to secuirty reasons, i have edited the names and shared it here

resource "dynatrace_management_zone" "aikeyan" {
	metadata {
		cluster_version = "1.210.105.20210216-141308"
		configuration_versions = [ 0 ]
	}
	name = "aikeyan"
	rules {
		enabled = true
		type = "CLOUD_APPLICATION"
		conditions {
			string_comparison {
				value = "AIkeyan"
				type = "STRING"
				negate = false
				case_sensitive = true
				operator = "EQUALS"
			}
			base_condition_key {
				attribute = "KUBERNETES_CLUSTER_NAME"
			}
		}
		conditions {
			string_comparison {
				type = "STRING"
				negate = false
				case_sensitive = true
				operator = "EQUALS"
				value = "aikeyan"
			}
			base_condition_key {
				attribute = "CLOUD_APPLICATION_NAMESPACE_NAME"
			}
		}
	}
}

resource "dynatrace_management_zone" "aikeyanr" {
	name = "aikeyanr"
	rules {
		conditions {
			string_comparison {
				operator = "EQUALS"
				value = "AI-Keyanr"
				type = "STRING"
				negate = false
				case_sensitive = true
			}
			base_condition_key {
				attribute = "KUBERNETES_CLUSTER_NAME"
			}
		}
		conditions {
			base_condition_key {
				attribute = "CLOUD_APPLICATION_NAMESPACE_NAME"
			}
			string_comparison {
				negate = false
				case_sensitive = true
				operator = "EQUALS"
				value = "aikeyanr"
				type = "STRING"
			}
		}
		conditions {
			string_comparison {
				type = "STRING"
				negate = false
				case_sensitive = true
				operator = "CONTAINS"
				value = "aikeyanr"
			}
			base_condition_key {
				attribute = "CLOUD_APPLICATION_NAME"
			}
		}
		enabled = true
		type = "CLOUD_APPLICATION"
	}
	metadata {
		cluster_version = "1.210.105.20210216-141308"
		configuration_versions = [ 0 ]
	}
}

resource "dynatrace_management_zone" "aikeyans" {
	rules {
		conditions {
			string_comparison {
				negate = false
				case_sensitive = true
				operator = "EQUALS"
				value = "AI-Keyans"
				type = "STRING"
			}
			base_condition_key {
				attribute = "KUBERNETES_CLUSTER_NAME"
			}
		}
		conditions {
			string_comparison {
				type = "STRING"
				negate = false
				case_sensitive = true
				operator = "EQUALS"
				value = "aikeyans"
			}
			base_condition_key {
				attribute = "CLOUD_APPLICATION_NAMESPACE_NAME"
			}
		}
		conditions {
			string_comparison {
				operator = "EQUALS"
				value = "aikeyans"
				type = "STRING"
				negate = false
				case_sensitive = true
			}
			base_condition_key {
				attribute = "CLOUD_APPLICATION_NAME"
			}
		}
		enabled = true
		type = "CLOUD_APPLICATION"
	}
	metadata {
		cluster_version = "1.210.105.20210216-141308"
		configuration_versions = [ 0 ]
	}
	name = "aikeyans"
}

**Comment by Karthikeyanraman94** [comment] 2021-04-26 07:42
I think its very common issue that had happened in many terraform providers  eg: https://github.com/hashicorp/terraform/issues/22349 .. if you have multiple management zones or tags in a file and if you apply to same DT environment, you would be getting this error I think

**Comment by Karthikeyanraman94** [comment] 2021-04-26 08:25
If this critical bug is fixed ASAP.. then we can start enjoy using this terraform provider with no hassle..
tried in the 1.0.6 version, same error...

3:51:57  ------------------------------------------------------------------------
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Canceled desc = context canceled
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Canceled desc = context canceled
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Canceled desc = context canceled
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Canceled desc = context canceled
13:52:03  
13:52:03  
13:52:03  
13:52:03  Error: rpc error: code = Unavailable desc = transport is closing
13:52:03  
13:52:03

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2021-04-26 10:44
Thank you for the samples. I CAN reproduce the issue - although not consistently. It seems to be some kind of race condition.
I DO have a plan to get around this, but I need to ask for patience until the end of the week before we can push out a fix for this.

**Comment by Karthikeyanraman94** [comment] 2021-04-26 11:24
Thanka @Dynatrace-Reinhard-Pilz

**Comment by Karthikeyanraman94** [comment] 2021-05-01 11:19
@Dynatrace-Reinhard-Pilz : please let us know if any updates, we are waiting for this fix heavily

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2021-05-03 07:46
Hello Karthikeyanraman94,

v1.0.7 just got released. It contains a complete re-write of the resource ```dynatrace_management_zone```, which finally deals with the issue at hand.

I've mentioned it already in the release notes, but also here as a reminder:

> Just a word of caution about using existing .tf files for management zones: The previous schema is still valid, but it was necessary to deprecate a lot of the properties and replace them with different ones. It's recommended to re-create these .tf files in order for terraform plan to be convinced that there are no changes left to be applied.

On the plus side you hopefully will be surprised in a pleasant way of the fact, that the whole resource ```dynatrace_management_zone``` is no well documented within the [Provider Documentation](https://registry.terraform.io/providers/dynatrace-oss/dynatrace/latest/docs/resources/management_zone).

**Closed by Dynatrace-Reinhard-Pilz** 2021-05-03 07:46 UTC
