### ISSUE TITLE
No Threshold Input Unit for `dynatrace_metric_events`

### ISSUE THREAD

**Issue by ilchebedelovski** [dynatrace-oss/terraform-provider-dynatrace#303] opened 2023-07-18 08:31 UTC
**Describe the bug**
I am using the `dynatrace_metric_events` resource with a Provider version 1.32.1 and I have issues related to the Threshold Input Unit. I have a Static Threshold for a Slowdown and I am not able to define the unit for the Threshold, initially I thought that `ms` is the default unit but then I figured out that the unit is changed randomly after the code is applied

**To Reproduce**
1. Create a metric event over `dynatrace_metric_events`
2. Define some static Threshold
3. Apply different values and monitor the value directly in Dynatrace
4. The Threshold unit in Anomaly Detection > Metric Events is changing randomly

**Expected behavior**
I suppose a Unit property is required for `dynatrace_metric_events`

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-07-21 12:04
Hello @ilchebedelovski,
I can confirm your observation here. It's unfortunately nothing that can get "fixed" from our side.

What's happening here is, that Dynatrace internally stores the threshold value in the base unit of the metric you've chosen here. 

The unit presented within the WebUI is getting chosen for you on a basis of "best fit". So, for example if the stored value is 6000 and the unit of the metric is milliseconds, the WebUI decides to present that as "6 seconds", assuming that it's easier for a human to read. 

That automatic choice (or even a different selection made by the user in the WebUI) has however not impact on how the value is getting stored (or delivered via REST API to the Terraform Provider). It will *always* get stored so it matches the unit of the chosen metric.

What I can offer here - in order to make it a bit more convenient to maintain - in Terraform is to introduce a computed attribute `unit`. That would at least allow you to look up via `terraform show` what unit you're required to stick with.

What we cannot do easily is to allow for that `unit` attribute to be chosen by the user. Technically I can think of a way to maintain that information just within the local state and look it up on demand. But that comes with the price of having to replicate the algorithms that are translating units within Terraform. That part is unfortunately doomed to always be one step behind, as soon as Dynatrace R&D decides to introduce additional / different sets of units.

Makes sense?

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-07-27 07:39
Hello @ilchebedelovski, I'm closing this ticket until further notice, since the behavior has been clarified.
If you believe a computed attribute `unit` would be helpful here, drop us a message and we can work on that.

thanks,
Reinhard

**Closed by Dynatrace-Reinhard-Pilz** 2023-07-27 07:39 UTC
Labels: bug
