### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by ahilmathewkb** [dynatrace-oss/terraform-provider-dynatrace#565] opened 2024-10-15 22:16 UTC
**Describe the bug**
Creating a new SLO caused this issue. The actual SLO was created in Dynatrace however terraform reported it as failed. 

```
When applying changes to module.slo-definitions.module.slo-definitions["my-newslo--performance-lag-PROD"].dynatrace_slo_v2.service_slo, provider "provider[\"registry.terraform.io/dynatrace-oss/dynatrace\"]" produced an unexpected new value: Root object was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

This is one of the many SLOs and every other SLO was created successfully. But this one keeps failing in terraform.

**To Reproduce**
Create SLOs using terraform.

provider version - 1.69.0
**Expected behavior**
SLOs are created successfully and terraform doesn't error out.

**Comment by Reinhard-Pilz-Dynatrace** [comment] 2024-10-16 10:05
Hello @ahilmathewkb 

Could you provide the HCL code for the SLO you're trying to apply? The issue you're describing doesn't happen with the samples we're testing against. It looks like a very specific SLO configuration is necessary to reproduce that behavior.

regards,
Reinhard

**Comment by Reinhard-Pilz-Dynatrace** [comment] 2024-11-08 12:11
Hello @ahilmathewkb, I'm closing this ticket until further notice. In case you're able to provide additional HCL code sample so we can reproduce the issue, just drop us a message and we will reopen the ticket.

**Closed by Reinhard-Pilz-Dynatrace** 2024-11-08 12:11 UTC
Labels: bug
