### ISSUE TITLE
Crash when adding exported request attribute to another tenant

### ISSUE THREAD

**Issue by gmichels** [dynatrace-oss/terraform-provider-dynatrace#152] opened 2022-10-24 21:10 UTC
**Describe the bug**
Plugin crashes when applying a specific exported request attribute into another tenant

```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "qa"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

dynatrace_request_attribute.EDI_999_Error: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with dynatrace_request_attribute.EDI_999_Error,
│   on request_attributes.tf line 50, in resource "dynatrace_request_attribute" "EDI_999_Error":
│   50: resource "dynatrace_request_attribute" "EDI_999_Error" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-dynatrace_v1.14.1 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 22 [running]:
github.com/dtcookie/dynatrace/api/config/requestattributes.(*MethodReference).UnmarshalHCL(0xc000b2af00, {0x1bd10d8, 0xc00082bc80})
        github.com/dtcookie/dynatrace/api/config/requestattributes@v1.0.10/method_reference.go:159 +0x84c
github.com/dtcookie/dynatrace/api/config/requestattributes.(*CapturedMethod).UnmarshalHCL(0xc00088e0f0, {0x1bd10d8, 0xc00082bc20})
        github.com/dtcookie/dynatrace/api/config/requestattributes@v1.0.10/captured_method.go:113 +0x49f
github.com/dtcookie/dynatrace/api/config/requestattributes.(*DataSource).UnmarshalHCL(0xc0002e6bd0, {0x1bd10d8, 0xc00082b840})
        github.com/dtcookie/dynatrace/api/config/requestattributes@v1.0.10/data_source.go:253 +0xef8
github.com/dtcookie/dynatrace/api/config/requestattributes.(*RequestAttribute).UnmarshalHCL(0xc0002e6b40, {0x1bd1150, 0xc000b3ff60})
        github.com/dtcookie/dynatrace/api/config/requestattributes@v1.0.10/request_attribute.go:151 +0x798
github.com/dynatrace-oss/terraform-provider-dynatrace/resources/requestattributes.Create({0x1bcbbe8, 0xc00030afc0}, 0xc000b2ad00, {0x18f9460?, 0xc00004efc0?})
        github.com/dynatrace-oss/terraform-provider-dynatrace/resources/requestattributes/resource.go:57 +0x99
github.com/dynatrace-oss/terraform-provider-dynatrace/logging.Enable.func1({0x1bcbbe8, 0xc00030afc0}, 0x0?, {0x18f9460, 0xc00004efc0})
        github.com/dynatrace-oss/terraform-provider-dynatrace/logging/logging.go:79 +0x83
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00053a700, {0x1bcbc20, 0xc000463170}, 0xd?, {0x18f9460, 0xc00004efc0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00053a700, {0x1bcbc20, 0xc000463170}, 0xc000531040, 0xc0002e8a00, {0x18f9460, 0xc00004efc0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001265a0, {0x1bcbc20?, 0xc000463050?}, 0xc0008409b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00024e1e0, {0x1bcbc20?, 0xc000462480?}, 0xc0002e2070)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a2e0c0?, 0xc00024e1e0}, {0x1bcbc20, 0xc000462480}, 0xc0002e2000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000466000, {0x1bd0780, 0xc000682ea0}, 0xc0002de000, 0xc0007c0f00, 0x2146120, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc000466000, {0x1bd0780, 0xc000682ea0}, 0xc0002de000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-dynatrace_v1.14.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

HCL in question (scrubbed):

```
resource "dynatrace_request_attribute" "EDI_999_Error" {
  name        = "EDI 999 Error"
  enabled     = true
  aggregation = "ALL_DISTINCT_VALUES"
  # confidential = false
  data_type     = "STRING"
  normalization = "ORIGINAL"
  # skip_personal_data_masking = false
  data_sources {
    enabled    = true
    source     = "METHOD_PARAM"
    technology = "DOTNET"
    methods {
      argument_index = 0
      capture        = "ARGUMENT"
      method {
        argument_types = ["MyAppDataContracts.Search.Response"]
        class_name     = "MyCompany.MyApp.Events.Factories.ResponseExtensions"
        method_name    = "Contains999Error"
        modifiers      = ["STATIC"]
        return_type    = "System.Boolean"
        visibility     = "PUBLIC"
      }
    }
    scope {
      tag_of_process_group = "App:MyApp"
    }
  }
}
```

**To Reproduce**
1. Export request attribute already configured in one tenant using the export functionality
2. Create HCL file with exported resource
3. Plan to be applied on a different tenant, changes will be present (creation, as expected)
4. Crashes while actually applying the changes

**Expected behavior**
Clean apply

Let me know if any other information is needed.

Thank you

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2022-10-25 08:48
Hello @gmichels

I can reproduce the error locally. Looks like our integration tests don't cover modifiers.
The issue will be fixed with the next release.

**Closed** 2022-10-25 12:10 UTC
Labels: bug
