### ISSUE TITLE
Not able to create DataExplorerTile in this provider using metric selector

### ISSUE THREAD

**Issue by VarshneyPrince** [dynatrace-oss/terraform-provider-dynatrace#227] opened 2023-04-11 09:10 UTC
I am trying to create the Dynatrace dashboard using terraform , I want to use the metric selector directly , but there is no option to do so. Plus the dynatrace is giving a warning to use new charts instead of old ones

**Comment by VarshneyPrince** [comment] 2023-04-11 10:56
Thank you so much! I will try this and will update if this works!

**Comment by VarshneyPrince** [comment] 2023-04-12 11:29
`

resource "dynatrace_json_dashboard" "dashboard-update" {
  contents = jsonencode(
    {
      
      "dashboardMetadata": {
        "name": "${var.PRODUCT}-${var.ENVIRONMENT}-dashboard",
        "shared": true,
        "owner": "Prince_Varshney@mckinsey.com",
        "dashboardFilter": {
          "timeframe": "-30m",
          "managementZone": {
            "id": var.MANAGEMENT_ZONE,
          }
        },
        "tags": [
          "11858"
        ],
        "hasConsistentColors": false
      },
      "tiles": [
        {
          "name": "Keycloak Dev API Response Time",
          "nameSize": "small",
          "tileType": "DATA_EXPLORER",
          "configured": true,
          "bounds": {
            "top": 0,
            "left": 456,
            "width": 456,
            "height": 266
          },
          "tileFilter": {
            "timeframe": "-30m",
            "managementZone": {
              "id": var.MANAGEMENT_ZONE,
            }
          },
          "isAutoRefreshDisabled": false,
          "customName": "Single value",
          "queries": [
            {
              "id": "A",
              "metric": "builtin:service.response.time",
              "spaceAggregation": "AUTO",
              "timeAggregation": "DEFAULT",
              "splitBy": [
                "dt.entity.service"
              ],
              "sortBy": "DESC",
              "filterBy": {
                "filterOperator": "AND",
                "nestedFilters": [
                  {
                    "filter": "dt.entity.service",
                    "filterType": "TAG",
                    "filterOperator": "OR",
                    "nestedFilters": [],
                    "criteria": [
                      {
                        "value": "k8s_namespace_name:${var.NAMESPACE}",
                        "evaluator": "IN"
                      }
                    ]
                  },
                  {
                    "filter": "dt.entity.service",
                    "filterType": "TAG",
                    "filterOperator": "OR",
                    "nestedFilters": [],
                    "criteria": [
                      {
                        "value": "k8s_pod_name:keycloak-*",
                        "evaluator": "IN"
                      }
                    ]
                  }
                ],
                "criteria": []
              },
              "limit": 100,
              "rate": "NONE",
              "enabled": true
            }
          ],
          "visualConfig": {
            "type": "HONEYCOMB",
            "global": {
              "hideLegend": false
            },
            "rules": [
              {
                "matcher": "A:",
                "unitTransform": "auto",
                "valueFormat": "auto",
                "properties": {
                  "color": "BLUE",
                  "seriesType": "LINE"
                },
                "seriesOverrides": []
              }
            ],
            "axes": {
              "xAxis": {
                "visible": true
              },
              "yAxes": []
            },
            "heatmapSettings": {
              "yAxis": "VALUE"
            },
            "thresholds": [
              {
                "axisTarget": "LEFT",
                "rules": [
                  {
                    "color": "#7dc540"
                  },
                  {
                    "color": "#f5d30f"
                  },
                  {
                    "color": "#dc172a"
                  }
                ],
                "queryId": "",
                "visible": true
              }
            ],
            "tableSettings": {
              "isThresholdBackgroundAppliedToCell": false
            },
            "graphChartSettings": {
              "connectNulls": false
            },
            "honeycombSettings": {
              "showHive": true,
              "showLegend": true,
              "showLabels": true
            }
          },
          "queriesSettings": {
            "resolution": ""
          },
          "metricExpressions": [
            "resolution=Inf&(builtin:service.response.time:filter(and(or(in(\"dt.entity.service\",entitySelector(\"type(service),tag(~\"k8s_namespace_name:${var.NAMESPACE}~\")\"))),or(in(\"dt.entity.service\",entitySelector(\"type(service),tag(~\"k8s_pod_name:keycloak-*~\")\"))))):splitBy(\"dt.entity.service\"):sort(value(auto,descending)):limit(100)):names"
          ]
        },
        {
      "name": "API-V2 Dev API Response Time",
      "nameSize": "small",
      "tileType": "DATA_EXPLORER",
      "configured": true,
      "bounds": {
        "top": 0,
        "left": 912,
        "width": 418,
        "height": 266
      },
      "tileFilter": {
        "timeframe": "-30m",
        "managementZone": {
          "id": var.MANAGEMENT_ZONE
        }
      },
      "isAutoRefreshDisabled": false,
      "customName": "API-V2 API Response Time",
      "queries": [
        {
          "id": "A",
          "metric": "builtin:service.response.time",
          "spaceAggregation": "AUTO",
          "timeAggregation": "DEFAULT",
          "splitBy": [
            "dt.entity.service"
          ],
          "sortBy": "DESC",
          "filterBy": {
            "filterOperator": "AND",
            "nestedFilters": [
              {
                "filter": "dt.entity.service",
                "filterType": "TAG",
                "filterOperator": "OR",
                "nestedFilters": [],
                "criteria": [
                  {
                    "value": "k8s_namespace_name:${var.NAMESPACE}",
                    "evaluator": "IN"
                  }
                ]
              },
              {
                "filter": "dt.entity.service",
                "filterType": "TAG",
                "filterOperator": "OR",
                "nestedFilters": [],
                "criteria": [
                  {
                    "value": "k8s_pod_name:api-v*-*",
                    "evaluator": "IN"
                  }
                ]
              }
            ],
            "criteria": []
          },
          "limit": 100,
          "rate": "NONE",
          "enabled": true
        }
      ],
      "visualConfig": {
        "type": "HONEYCOMB",
        "global": {
          "hideLegend": false
        },
        "rules": [
          {
            "matcher": "A:",
            "unitTransform": "auto",
            "valueFormat": "auto",
            "properties": {
              "color": "BLUE",
              "seriesType": "LINE"
            },
            "seriesOverrides": []
          }
        ],
        "axes": {
          "xAxis": {
            "visible": true
          },
          "yAxes": []
        },
        "heatmapSettings": {
          "yAxis": "VALUE"
        },
        "thresholds": [
          {
            "axisTarget": "LEFT",
            "rules": [
              {
                "color": "#7dc540"
              },
              {
                "color": "#f5d30f"
              },
              {
                "color": "#dc172a"
              }
            ],
            "queryId": "",
            "visible": true
          }
        ],
        "tableSettings": {
          "isThresholdBackgroundAppliedToCell": false
        },
        "graphChartSettings": {
          "connectNulls": false
        },
        "honeycombSettings": {
          "showHive": true,
          "showLegend": true,
          "showLabels": true
        }
      },
      "queriesSettings": {
        "resolution": ""
      },
      "metricExpressions": [
        "resolution=Inf&(builtin:service.response.time:filter(and(or(in(\"dt.entity.service\",entitySelector(\"type(service),tag(~\"k8s_pod_name:api-v*-*~\")\"))),or(in(\"dt.entity.service\",entitySelector(\"type(service),tag(~\"k8s_namespace_name:${var.NAMESPACE}~\")\"))))):splitBy(\"dt.entity.service\"):sort(value(auto,descending)):limit(100)):names"
      ]
    }
      ]
    }
  )
}

`

**Comment by Dynatrace-Reinhard-Pilz** [comment] 2023-04-12 13:08
That behavior is surprising. The Provider as a matter of fact "injects" that `id` attribute before sending the request to the REST API - or at least it is supposed to. What makes things even more interesting is, that I cannot reproduce the issue locally with your example (I just replaced the variables with actual values.

Let's narrow down the actual environment here a bit.
* What version of the Terraform Provider are you using?
* What OS are you executing Terraform on?
* Is your Dynatrace Environment SaaS (`https://#####.live.dynatrace.com`) or Managed (`https://###/e/#####`)?

In addition to that could you execute `terraform apply` with the environment variable `DYNATRACE_LOG_HTTP=terraform-provider-dynatrace.http.log` set? That should create a log file containing the exact HTTP payload that's being sent.

We can also take a look at the situation together during a Zoom call. We just need to find a 30 min window that works for both of us. I'm located in Central Europe. Feel free to reach out to me at reinhard.pilz@dynatrace.com if you'd like to schedule such a call tomorrow or Friday.

**Comment by VarshneyPrince** [comment] 2023-05-01 16:33
Sorry! I was not able to follow up on this as I was on PTO! I have used dynatrace_dashboard for now instead of dynatrace_json_dashboard.

**Comment by kishikawa12** [comment] 2023-08-23 20:13
Hi @VarshneyPrince,

I've been reviewing all of our open GitHub issues and wanted to follow-up on this ticket. Just to validate, I created the dashboard with your example and wasn't able to reproduce the issue (dashboard created successfully). Based off of your last comment, it sounds like you may have found a workaround with the `dynatrace_dashboard` resource. Would you like to continue troubleshooting this issue? If not, I can go ahead and close this ticket for the time being.

Thanks!

**Closed** 2023-08-31 18:21 UTC
