### ISSUE TITLE
Openpipeline logs deleting all existing pipelines 

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [dynatrace-oss/terraform-provider-dynatrace#568] opened 2024-10-18 06:05 UTC
**Describe the bug**
We tried updating one of the pipeline which resulted in deleting all existing pipelines. The pipeline updation was successful but rest of the custom pipelines got deleted. 

**To Reproduce**
1. Update a existing pipeline using the module resource "dynatrace_openpipeline_logs".
2. Run terraform plan and apply.
3. Check for the changes under logs in Openpipeline.
4. All the existing pipelines deleted

**Expected behavior**
The module "dynatrace_openpipeline_logs" should just update resource targetted in the code. All other existing pipelines should not have any impact.

**Screenshots**
Attaching log for your reference.

Thanks,
Vijayalakshmi

[tf_log.txt](https://github.com/user-attachments/files/17429013/tf_log.txt)

**Comment by arthurpitman** [comment] 2024-10-18 14:21
Hi @Vijayalakshmi-Yolbhavi , thank you for the valuable feedback!

Currently this behavior is by-design: `dynatrace_openpipeline_logs` is a singleton resource that must contain all custom pipelines, endpoints and routing entries for the OpenPipeline logs configuration.

We are investigating if and how to better expose these elements are individual resources.

**Comment by Reinhard-Pilz-Dynatrace** [comment] 2024-10-21 09:43
Hello @Vijayalakshmi-Yolbhavi I'm closing this ticket, as it's more or less a duplicate of #561. Feel free to contribute on that other ticket, once @arthurpitman is able to provide an outlook there.

**Closed by Reinhard-Pilz-Dynatrace** 2024-10-21 09:43 UTC
Labels: bug
